export const APP_RESET_PROJECT_DATA = 'APP.RESET_PROJECT_DATA';
export const APP_FETCH_USER_MEMBERSHIPS = 'APP.FETCH_USER_MEMBERSHIPS';
export const APP_FETCHED_USER_MEMBERSHIPS = 'APP.FETCHED_USER_MEMBERSHIPS';
export const APP_AGGREGATED_USER_PERMISSIONS =
  'APP.AGGREGATED_USER_PERMISSIONS';

export const APP_FETCH_SERVICES_AVAILABILITY_SUCCESS = `APP_FETCH_SERVICES_AVAILABILITY_SUCCESS`;

export const APP_FETCH_TITLE_ENVIRONMENT = `APP_FETCH_TITLE_ENVIRONMENT`;
export const APP_FETCH_TITLE_ENVIRONMENT_SUCCESS = `APP_FETCH_TITLE_ENVIRONMENT_SUCCESS`;
