const prefix = 'playpants/SCHEDULE_STORIES_DETAILS';

export const FETCH_CATEGORIES = `${prefix}.CATEGORIES`;
export const FETCH_CONTEXTS = `${prefix}.CONTEXTS`;
export const FETCH_SCHEDULE_STORY_EVENTS_COUNT = `${prefix}.FETCH_SCHEDULE_STORY_EVENTS_COUNT`;
export const FETCH_SCHEDULE_STORY_EVENTS_COUNT_SUCCESS = `${prefix}.FETCH_SCHEDULE_STORY_EVENTS_COUNT_SUCCESS`;
export const FETCH_SCHEDULE_STORY_EVENTS_COUNT_FAILED = `${prefix}.FETCH_SCHEDULE_STORY_EVENTS_COUNT_FAILED`;
