const PREFIX = 'object-store/';

export const FORM_NAME = 'EDIT_STATISTICS_VALUE_FORM';

export const FETCH_OBJECT_STATS = `${PREFIX}FETCH_OBJECT_STATS`;
export const FETCH_OBJECT_STAT_SUCCESS = `${PREFIX}FETCH_OBJECT_STAT_SUCCESS`;

export const UPDATE_STATISTIC_VALUE = `${PREFIX}UPDATE_STATISTIC_VALUE`;

export const UPDATE_STATISTIC_VALUE_SUCCESS = `${PREFIX}UPDATE_STATISTIC_VALUE_SUCCESS`;

export const REFRESH_TABLE = `${PREFIX}REFRESH_TABLE`;
