export const CONTENT_TYPE_FETCH = 'CONTENT_TYPE_FETCH';
export const CONTENT_TYPE_FETCH_SUCCESS = 'CONTENT_TYPE_FETCH_SUCCESS';
export const CONTENT_TYPE_FETCH_FAIL = 'CONTENT_TYPE_FETCH_FAIL';

export const OBJECT_PERMISSIONS_FETCH = 'OBJECT_PERMISSIONS_FETCH';
export const OBJECT_PERMISSIONS_FETCH_SUCCESS =
  'OBJECT_PERMISSIONS_FETCH_SUCCESS';
export const OBJECT_PERMISSIONS_FETCH_FAIL = 'OBJECT_PERMISSIONS_FETCH_FAIL';

export const COMPANIES_FETCH = 'COMPANIES_FETCH';
export const COMPANIES_FETCH_SUCCESS = 'COMPANIES_FETCH_SUCCESS';
export const COMPANIES_FETCH_FAIL = 'COMPANIES_FETCH_FAIL';

export const COMPANY_GROUPS_FETCH = 'COMPANY_GROUPS_FETCH';
export const COMPANY_GROUPS_FETCH_SUCCESS = 'COMPANY_GROUPS_FETCH_SUCCESS';
export const COMPANY_GROUPS_FETCH_FAIL = 'COMPANY_GROUPS_FETCH_FAIL';

export const GRANT_PERMISSIONS = 'GRANT_PERMISSIONS';
export const GRANT_PERMISSIONS_SUCCESS = 'GRANT_PERMISSIONS_SUCCESS';
export const GRANT_PERMISSIONS_FAIL = 'GRANT_PERMISSIONS_FAIL';

export const REVOKE_PERMISSIONS = 'REVOKE_PERMISSIONS';
export const REVOKE_PERMISSIONS_SUCCESS = 'REVOKE_PERMISSIONS_SUCCESS';
export const REVOKE_PERMISSIONS_FAIL = 'REVOKE_PERMISSIONS_FAIL';
export const FETCH_RELATED_PERMISSONS = 'FETCH_RELATED_PERMISSONS';
export const FETCH_RELATED_PERMISSONS_SUCCESS =
  'FETCH_RELATED_PERMISSONS_SUCCESS';
