export const TASK_RULES_SEARCH = 'security/TASK_RULES_SEARCH';

export const TASK_RULES_FETCH = 'security/TASK_RULES_FETCH';
export const TASK_RULES_FETCH_SUCCESS = 'security/TASK_RULES_FETCH_SUCCESS';

export const TASK_RULES_SERVICE_AND_TASK_INFO_FETCH =
  'security/TASK_RULES_SERVICE_AND_TASK_INFO_FETCH';
export const TASK_RULES_SERVICE_AND_TASK_INFO_FETCH_SUCCESS =
  'security/TASK_RULES_SERVICE_AND_TASK_INFO_FETCH_SUCCESS';

export const TASK_RULES_ADD_MODAL_OPEN = 'security/TASK_RULES_ADD_MODAL_OPEN';
export const TASK_RULES_ADD_MODAL_CLOSE = 'security/TASK_RULES_ADD_MODAL_CLOSE';
export const TASK_RULES_ADD = 'security/TASK_RULES_ADD';
export const TASK_RULES_ADD_SUCCESS = 'security/TASK_RULES_ADD_SUCCESS';
export const TASK_RULES_ADD_FAILED = 'security/TASK_RULES_ADD_FAILED';

export const TASK_RULES_DELETE = 'security/TASK_RULES_DELETE';
export const TASK_RULES_DELETE_SUCCESS = 'security/TASK_RULES_DELETE_SUCCESS';
