export const MODAL_OPEN = 'COMPONENTS.COMMON.MODAL_OPEN';
export const MODAL_CLOSE = 'COMPONENTS.COMMON.MODAL_CLOSE';

export const MODAL_SUBMIT = 'COMPONENTS.COMMON.MODAL_SUBMIT';
export const MODAL_STOP_SUBMITTING = 'COMPONENTS.COMMON.MODAL_STOP_SUBMITTING';
