// Prefix
export const LOGIN_QUEUE_STATUS = 'LOGIN_QUEUE_STATUS';
export const LOGIN_QUEUE_VIP_LIST = 'LOGIN_QUEUE_VIP_LIST';
// Put
export const LOGIN_QUEUE_SPECIFIC_SETTINGS = 'LOGIN_QUEUE_SPECIFIC_SETTINGS';
export const LOGIN_QUEUE_SPECIFIC_SETTINGS_SUCCESS =
  'LOGIN_QUEUE_SPECIFIC_SETTINGS_SUCCESS';
export const LOGIN_QUEUE_SPECIFIC_SETTINGS_FAILED =
  'LOGIN_QUEUE_SPECIFIC_SETTINGS_FAILED';

export const LOGIN_QUEUE_TITLE_SETTINGS = 'LOGIN_QUEUE_TITLE_SETTINGS';
export const LOGIN_QUEUE_TITLE_SETTINGS_SUCCESS =
  'LOGIN_QUEUE_TITLE_SETTINGS_SUCCESS';
export const LOGIN_QUEUE_TITLE_SETTINGS_FAILED =
  'LOGIN_QUEUE_TITLE_SETTINGS_FAILED';
// Patch
export const LOGIN_QUEUE_VIP_LIST_SUCCESS = 'LOGIN_QUEUE_VIP_LIST_SUCCESS';
export const LOGIN_QUEUE_VIP_LIST_FAILED = 'LOGIN_QUEUE_VIP_LIST_FAILED';
