export const CHALLENGE_GENERATION_LOGS_FETCH =
  'security/CHALLENGE_GENERATION_LOGS_FETCH';
export const CHALLENGE_GENERATION_LOGS_FETCH_SUCCESS =
  'security/CHALLENGE_GENERATION_LOGS_FETCH_SUCCESS';

export const CHALLENGE_GENERATION_LOGS_CHANGE_SEARCH_QUERY =
  'security/CHALLENGE_GENERATION_LOGS_CHANGE_SEARCH_QUERY';

export const CHALLENGE_GENERATION_LOGS_CHANGE_ORDER =
  'security/CHALLENGE_GENERATION_LOGS_CHANGE_ORDER';
