export const CONNECTION_LOGS_FETCH = 'security/CONNECTION_LOGS_BY_USER_FETCH';
export const CONNECTION_LOGS_FETCH_SUCCESS =
  'security/CONNECTION_LOGS_BY_USER_FETCH_SUCCESS';

export const CONNECTION_LOGS_CHANGE_USER_ID =
  'security/CONNECTION_LOGS_CHANGE_USER_ID';
export const CONNECTION_LOGS_CHANGE_ASCENDING =
  'security/CONNECTION_LOGS_CHANGE_ASCENDING';

export const TOGGLE_TEST_USERS_ENTRIES = 'security/TOGGLE_TEST_USERS_ENTRIES';
