export const ACCOUNTS_DASHBOARD_KPIS_FETCH =
  'accounts-dashboard/ACCOUNTS_DASHBOARD_KPIS_FETCH';
export const ACCOUNTS_DASHBOARD_KPIS_FETCH_SUCCESS =
  'accounts-dashboard/ACCOUNTS_DASHBOARD_KPIS_FETCH_SUCCESS';
export const ACCOUNTS_DASHBOARD_KPIS_FETCH_FAILED =
  'accounts-dashboard/ACCOUNTS_DASHBOARD_KPIS_FETCH_FAILED';

export const ACCOUNTS_DASHBOARD_PRIVACY_KPIS =
  'accounts-dashboard/ACCOUNTS_DASHBOARD_PRIVACY_KPIS';
export const ACCOUNTS_DASHBOARD_PRIVACY_KPIS_TOTALS =
  'accounts-dashboard/ACCOUNTS_DASHBOARD_PRIVACY_KPIS_TOTALS';
export const ACCOUNTS_DASHBOARD_PRIVACY_KPIS_PER_COUNTRY =
  'accounts-dashboard/ACCOUNTS_DASHBOARD_PRIVACY_KPIS_PER_COUNTRY';
