export const LEADERBOARDS_FETCH = 'leaderboards/LEADERBOARDS_FETCH';
export const LEADERBOARDS_FETCH_SUCCESS =
  'leaderboards/LEADERBOARDS_FETCH_SUCCESS';
export const LEADERBOARDS_FETCH_FAILED =
  'leaderboards/LEADERBOARDS_FETCH_FAILED';

export const LEADERBOARDS_LIST_ITEM_ONCLICK =
  'leaderboards/LEADERBOARDS_LIST_ITEM_ONCLICK';

export const LEADERBOARDS_RESET = 'leaderboards/LEADERBOARDS_RESET';
export const LEADERBOARDS_FETCH_STATUS =
  'leaderboards/LEADERBOARDS_FETCH_STATUS';
export const LEADERBOARDS_FETCH_STATUS_SUCCESS =
  'leaderboards/LEADERBOARDS_FETCH_STATUS_SUCCESS';
