const PREFIX = 'object-store/';

export {
  START_UPLOAD_PROGRESS,
  INCREMENT_UPLOAD_PROGRESS,
  STOP_UPLOAD_PROGRESS,
  FAIL_UPLOAD_PROGRESS,
  UPLOAD_OBJECT,
} from '../actionTypes';

export const ADD_CATEGORY = `${PREFIX}ADD_CATEGORY`;

export const MULTI_PUBLISHER_OBJECT_DOWNLOAD = `${PREFIX}MULTI_PUBLISHER_OBJECT_DOWNLOAD`;
export const MULTI_PUBLISHER_OBJECT_DOWNLOAD_SUCCESS = `${MULTI_PUBLISHER_OBJECT_DOWNLOAD}_SUCCESS`;
