version: "3.7"
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "ci:e2e:prod"]
