export const STORAGE_POOLED_FILES_FETCH = 'storage/STORAGE_POOLED_FILES_FETCH';
export const STORAGE_POOLED_FILES_FETCH_SUCCESS =
  'storage/STORAGE_POOLED_FILES_FETCH_SUCCESS';

export const STORAGE_POOLED_FILES_LIST_ITEM_ONCLICK =
  'storage/STORAGE_POOLED_FILES_LIST_ITEM_ONCLICK';

export const STORAGE_POOLED_FILES_UPLOAD =
  'storage/STORAGE_POOLED_FILES_UPLOAD';
export const STORAGE_POOLED_FILES_UPLOAD_SUCCESS =
  'storage/STORAGE_POOLED_FILES_UPLOAD_SUCCESS';

export const STORAGE_POOLED_FILES_DELETE =
  'storage/STORAGE_POOLED_FILES_DELETE';
export const STORAGE_POOLED_FILES_DELETE_SUCCESS =
  'storage/STORAGE_POOLED_FILES_DELETE_SUCCESS';

export const STORAGE_POOLED_FILES_DOWNLOAD =
  'storage/STORAGE_POOLED_FILES_DOWNLOAD';
export const STORAGE_POOLED_FILES_DOWNLOAD_SUCCESS =
  'storage/STORAGE_POOLED_FILES_DOWNLOAD_SUCCESS';

export const STORAGE_POOLED_FILES_SUMMARY_DELETE =
  'storage/STORAGE_POOLED_FILES_SUMMARY_DELETE';
export const STORAGE_POOLED_FILES_SUMMARY_DELETE_SUCCESS =
  'storage/STORAGE_POOLED_FILES_SUMMARY_DELETE_SUCCESS';

export const STORAGE_POOLED_FILES_SUMMARY_DOWNLOAD =
  'storage/STORAGE_POOLED_FILES_SUMMARY_DOWNLOAD';
export const STORAGE_POOLED_FILES_SUMMARY_DOWNLOAD_SUCCESS =
  'storage/STORAGE_POOLED_FILES_SUMMARY_DOWNLOAD_SUCCESS';
