export const CONNECTION_LOGS_FETCH = 'security/CONNECTION_LOGS_BY_TIME_FETCH';
export const CONNECTION_LOGS_FETCH_SUCCESS =
  'security/CONNECTION_LOGS_BY_TIME_FETCH_SUCCESS';
export const TOGGLE_TEST_USERS_ENTRIES = 'security/TOGGLE_TEST_USERS_ENTRIES';
