export const IP_CONTROL_SEARCH = 'security/IP_CONTROL_SEARCH';

export const IP_CONTROL_FETCH = 'security/IP_CONTROL_FETCH';
export const IP_CONTROL_FETCH_SUCCESS = 'security/IP_CONTROL_FETCH_SUCCESS';

export const IP_CONTROL_FETCH_ALL = 'security/IP_CONTROL_FETCH_ALL';
export const IP_CONTROL_FETCH_ALL_SUCCESS =
  'security/IP_CONTROL_FETCH_ALL_SUCCESS';

export const IP_CONTROL_FETCH_GROUPS = 'security/IP_CONTROL_FETCH_GROUPS';
export const IP_CONTROL_FETCH_NOTES = 'security/IP_CONTROL_FETCH_NOTES';
export const IP_CONTROL_FETCH_GROUPS_SUCCESS =
  'security/IP_CONTROL_FETCH_GROUPS_SUCCESS';
export const IP_CONTROL_FETCH_NOTES_SUCCESS =
  'security/IP_CONTROL_FETCH_NOTES_SUCCESS';

export const IP_CONTROL_ADD_NOTE = 'security/IP_CONTROL_NOTE_ADD';
export const IP_CONTROL_ADD_NOTE_SUCCESS =
  'security/IP_CONTROL_ADD_NOTE_SUCCESS';
export const IP_CONTROL_ADD_NOTE_FAILED = 'security/IP_CONTROL_ADD_NOTE_FAILED';

export const IP_CONTROL_UPDATE_NOTE = 'security/IP_CONTROL_NOTE_UPDATE';
export const IP_CONTROL_UPDATE_NOTE_SUCCESS =
  'security/IP_CONTROL_UPDATE_NOTE_SUCCESS';
export const IP_CONTROL_UPDATE_NOTE_FAILED =
  'security/IP_CONTROL_UPDATE_NOTE_FAILED';

export const IP_CONTROL_DELETE_NOTE = 'security/IP_CONTROL_NOTE_DELETE';
export const IP_CONTROL_DELETE_NOTE_SUCCESS =
  'security/IP_CONTROL_DELETE_NOTE_SUCCESS';
export const IP_CONTROL_DELETE_NOTE_FAILED =
  'security/IP_CONTROL_DELETE_NOTE_FAILED';

export const IP_CONTROL_ADD_GROUP = 'security/IP_CONTROL_GROUP_ADD';
export const IP_CONTROL_ADD_GROUP_SUCCESS =
  'security/IP_CONTROL_ADD_GROUP_SUCCESS';
export const IP_CONTROL_ADD_GROUP_FAILED =
  'security/IP_CONTROL_ADD_GROUP_FAILED';

export const IP_CONTROL_DELETE_GROUP = 'security/IP_CONTROL_GROUP_DELETE';
export const IP_CONTROL_DELETE_GROUP_SUCCESS =
  'security/IP_CONTROL_DELETE_GROUP_SUCCESS';
export const IP_CONTROL_DELETE_GROUP_FAILED =
  'security/IP_CONTROL_DELETE_GROUP_FAILED';

export const IP_CONTROL_ADD_MODAL_OPEN = 'security/IP_CONTROL_ADD_MODAL_OPEN';
export const IP_CONTROL_ADD_MODAL_CLOSE = 'security/IP_CONTROL_ADD_MODAL_CLOSE';
export const IP_CONTROL_ADD = 'security/IP_CONTROL_ADD';
export const IP_CONTROL_ADD_SUCCESS = 'security/IP_CONTROL_ADD_SUCCESS';
export const IP_CONTROL_ADD_FAILED = 'security/IP_CONTROL_ADD_FAILED';

export const IP_CONTROL_DELETE = 'security/IP_CONTROL_DELETE';
export const IP_CONTROL_DELETE_SUCCESS = 'security/IP_CONTROL_DELETE_SUCCESS';

export const WHITELISTED_USERS_FETCH = 'security/WHITELISTED_USERS_FETCH';
export const WHITELISTED_USERS_FETCH_SUCCESS =
  'security/WHITELISTED_USERS_FETCH_SUCCESS';
