import {
  FETCH_FRANCHISE_DATA,
  FETCH_FRANCHISE_DATA_SUCCESS,
} from './scenes/Dashboard/actionTypes';

const REPORTING_FETCH_FRANCHISES = 'REPORTING_FETCH_FRANCHISES';
const REPORTING_FETCH_FRANCHISES_SUCCESS = 'REPORTING_FETCH_FRANCHISES_SUCCESS';
const REPORTING_FETCH_FRANCHISES_FAILED = 'REPORTING_FETCH_FRANCHISES_FAILED';

export {
  FETCH_FRANCHISE_DATA,
  FETCH_FRANCHISE_DATA_SUCCESS,
  REPORTING_FETCH_FRANCHISES,
  REPORTING_FETCH_FRANCHISES_SUCCESS,
  REPORTING_FETCH_FRANCHISES_FAILED,
};
