export const CHANGE_PROJECT = 'PROJECT_SELECTOR.CHANGE_PROJECT';
export const CONFIGURED_PROJECTS_FETCH = 'CONFIGURED_PROJECTS_FETCH';
export const CONFIGURED_PROJECTS_FETCH_SUCCESS =
  'CONFIGURED_PROJECTS_FETCH_SUCCESS';
export const CONFIGURED_PROJECTS_FETCH_FAILED =
  'CONFIGURED_PROJECTS_FETCH_FAILED';
