export const UPLOAD_SCRIPT_POST = 'lootGen/ASSET_CHANGE_POST';
export const UPLOAD_SCRIPT_POST_SUCCESS = 'lootGen/UPLOAD_SCRIPT_POST_SUCCESS';
export const UPLOAD_SCRIPT_POST_FAILED = 'lootGen/UPLOAD_SCRIPT_POST_FAILED';

export const UPLOAD_SCRIPT_CLOSE_MODAL = 'lootGen/UPLOAD_SCRIPT_CLOSE_MODAL';
export const UPLOAD_SCRIPT_OPEN_MODAL = 'lootGen/UPLOAD_SCRIPT_OPEN_MODAL';
