export const USER_CONTEXT_STORAGE_RELOAD_DETAILS =
  'storage/USER_CONTEXT_STORAGE_RELOAD_DETAILS';
export const USER_CONTEXT_STORAGE_FETCH = 'storage/USER_CONTEXT_STORAGE_FETCH';
export const USER_CONTEXT_STORAGE_FETCH_SUCCESS =
  'storage/USER_CONTEXT_STORAGE_FETCH_SUCCESS';

export const USER_CONTEXT_STORAGE_LIST_ITEM_ONCLICK =
  'storage/USER_CONTEXT_STORAGE_LIST_ITEM_ONCLICK';

export const USER_CONTEXT_STORAGE_FILES_UPLOAD_CLOSE_MODAL =
  'storage/USER_CONTEXT_STORAGE_FILES_UPLOAD_CLOSE_MODAL';
export const USER_CONTEXT_STORAGE_FILES_UPLOAD_OPEN_MODAL =
  'storage/USER_CONTEXT_STORAGE_FILES_UPLOAD_OPEN_MODAL';
export const USER_CONTEXT_STORAGE_FILES_UPLOAD =
  'storage/USER_CONTEXT_STORAGE_FILES_UPLOAD';
export const USER_CONTEXT_STORAGE_FILES_UPLOAD_SUCCESS =
  'storage/USER_CONTEXT_STORAGE_FILES_UPLOAD_SUCCESS';

export const USER_CONTEXT_STORAGE_GET_STORAGE_CONTEXTS =
  'storage/USER_CONTEXT_STORAGE_GET_STORAGE_CONTEXTS';
export const USER_CONTEXT_STORAGE_GET_STORAGE_CONTEXTS_SUCCESS =
  'storage/USER_CONTEXT_STORAGE_GET_STORAGE_CONTEXTS_SUCCESS';
