const prefix = 'playpants/GROUP_STORIES_SIDEBAR';

export const SET_SELECTED_EVENT = `${prefix}.SET_SELECTED_EVENT`;
export const SET_SELECTED_THEN_OPEN = `${prefix}.SET_SELECTED_THEN_OPEN`;
export const RESET = `${prefix}.RESET`;

export const REMOVE_GROUP_STORY_FROM_EVENT = `${prefix}.REMOVE_GROUP_STORY_FROM_EVENT`;
export const REMOVE_GROUP_STORY_FROM_EVENT_SUCCESS = `${prefix}.REMOVE_GROUP_STORY_FROM_EVENT_SUCCESS`;
export const REMOVE_GROUP_STORY_FROM_EVENT_FAILED = `${prefix}.REMOVE_GROUP_STORY_FROM_EVENT_FAILED`;

export const FETCH_ALL_GROUP_STORY_EVENTS = `${prefix}.ALL_GROUP_STORY_EVENTS_FETCH`;
export const FETCH_ALL_GROUP_STORY_EVENTS_SUCCESS = `${prefix}.ALL_GROUP_STORY_EVENTS_FETCH_SUCCESS`;
export const FETCH_ALL_GROUP_STORY_EVENTS_FAILED = `${prefix}.ALL_GROUP_STORY_EVENTS_FETCH_FAILED`;

export const FETCH_GROUP_STORY_THEN_SELECT = `${prefix}.FETCH_GROUP_STORY_THEN_SELECT`;
export const FETCH_GROUP_STORY_THEN_SELECT_SUCCESS = `${FETCH_GROUP_STORY_THEN_SELECT}_SUCCESS`;
export const FETCH_GROUP_STORY_THEN_SELECT_FAILED = `${FETCH_GROUP_STORY_THEN_SELECT}_FAILED`;

export const RESET_GROUP_STORIES_SIDEBAR = `${prefix}.RESET_GROUP_STORIES_SIDEBAR`;
