export const LEADERBOARD_DATA_FETCH = 'leaderboards/LEADERBOARD_DATA_FETCH';
export const LEADERBOARD_DATA_FETCH_SUCCESS =
  'leaderboards/LEADERBOARD_DATA_FETCH_SUCCESS';

export const LEADERBOARD_DELETE_ENTITIES =
  'leaderboards/LEADERBOARD_DELETE_ENTITIES';
export const LEADERBOARD_DELETE_ENTITIES_SUCCESS =
  'leaderboards/LEADERBOARD_DELETE_ENTITIES_SUCCESS';

export const LEADERBOARD_RESET = 'leaderboards/LEADERBOARD_RESET';
export const LEADERBOARD_RESET_SUCCESS =
  'leaderboards/LEADERBOARD_RESET_SUCCESS';
