export const STORAGE_VARIABLES_SETS_FETCH =
  'storage/STORAGE_VARIABLES_SETS_FETCH';
export const STORAGE_VARIABLES_SETS_FETCH_SUCCESS =
  'storage/STORAGE_VARIABLES_SETS_FETCH_SUCCESS';
export const STORAGE_VARIABLES_SETS_FETCH_FAILED =
  'storage/STORAGE_VARIABLES_SETS_FETCH_FAILED';

export const STORAGE_VARIABLES_SETS_LIST_ITEM_ONCLICK =
  'storage/STORAGE_VARIABLES_SETS_LIST_ITEM_ONCLICK';
export const STORAGE_VARIABLES_SETS_FETCH_DETAILS_SUCCESS =
  'storage/STORAGE_VARIABLES_SETS_FETCH_DETAILS_SUCCESS';

export const STORAGE_VARIABLES_SETS_OPEN_ADD_MODAL =
  'storage/STORAGE_VARIABLES_SETS_OPEN_ADD_MODAL';
export const STORAGE_VARIABLES_SETS_CLOSE_ADD_MODAL =
  'storage/STORAGE_VARIABLES_SETS_CLOSE_ADD_MODAL';
export const STORAGE_VARIABLES_SETS_ADD = 'storage/STORAGE_VARIABLES_SETS_ADD';
export const STORAGE_VARIABLES_SETS_ADD_SUCCESS =
  'storage/STORAGE_VARIABLES_SETS_ADD_SUCCESS';

export const STORAGE_VARIABLES_SET_DELETE =
  'storage/STORAGE_VARIABLES_SET_DELETE';
export const STORAGE_VARIABLES_SET_DELETE_SUCCESS =
  'storage/STORAGE_VARIABLES_SET_DELETE_SUCCESS';

export const STORAGE_VARIABLES_SETS_FETCH_VARIABLES_SETS_DETAILS =
  'storage/STORAGE_VARIABLES_SETS_FETCH_VARIABLES_SETS_DETAILS';
export const STORAGE_VARIABLES_SETS_FETCH_VARIABLES_SETS_DETAILS_SUCCESS =
  'storage/STORAGE_VARIABLES_SETS_FETCH_VARIABLES_SETS_DETAILS_SUCCESS';

export const STORAGE_VARIABLES_SET_UPDATE =
  'storage/STORAGE_VARIABLES_SET_UPDATE';
export const STORAGE_VARIABLES_SET_UPDATE_SUCCESS =
  'storage/STORAGE_VARIABLES_SET_UPDATE_SUCCESS';

export const STORAGE_VARIABLES_SET_PROPAGATE =
  'storage/STORAGE_VARIABLES_SET_PROPAGATE';
