import * as AT from 'playpants/components/ScheduleComponent/actionTypes';

export const SCOPE = 'playpants/SCHEDULE';

export const FETCH_EVENT_MANAGER_EVENTS = SCOPE + AT.FETCH_EVENT_MANAGER_EVENTS;
export const FETCH_EVENT_MANAGER_EVENTS_FAILED =
  SCOPE + AT.FETCH_EVENT_MANAGER_EVENTS_FAILED;
export const FETCH_EVENT_MANAGER_EVENTS_SUCCESS =
  SCOPE + AT.FETCH_EVENT_MANAGER_EVENTS_SUCCESS;

export const FETCH_EXTERNAL_EVENTS = SCOPE + AT.FETCH_EXTERNAL_EVENTS;
export const FETCH_EXTERNAL_EVENTS_FAILED =
  SCOPE + AT.FETCH_EXTERNAL_EVENTS_FAILED;
export const FETCH_EXTERNAL_EVENTS_SUCCESS =
  SCOPE + AT.FETCH_EXTERNAL_EVENTS_SUCCESS;

export const FETCH_INFORMATIONAL_EVENTS = SCOPE + AT.FETCH_INFORMATIONAL_EVENTS;
export const FETCH_INFORMATIONAL_EVENTS_FAILED =
  SCOPE + AT.FETCH_INFORMATIONAL_EVENTS_FAILED;
export const FETCH_INFORMATIONAL_EVENTS_SUCCESS =
  SCOPE + AT.FETCH_INFORMATIONAL_EVENTS_SUCCESS;

export const FETCH_DEMONWARE_EVENTS = SCOPE + AT.FETCH_DEMONWARE_EVENTS;
export const FETCH_DEMONWARE_EVENTS_FAILED =
  SCOPE + AT.FETCH_DEMONWARE_EVENTS_FAILED;
export const FETCH_DEMONWARE_EVENTS_SUCCESS =
  SCOPE + AT.FETCH_DEMONWARE_EVENTS_SUCCESS;

export const FETCH_AB_TESTS = SCOPE + AT.FETCH_AB_TESTS;
export const FETCH_AB_TESTS_FAILED = SCOPE + AT.FETCH_AB_TESTS_FAILED;
export const FETCH_AB_TESTS_SUCCESS = SCOPE + AT.FETCH_AB_TESTS_SUCCESS;

export const FETCH_EXPY_TESTS = SCOPE + AT.FETCH_EXPY_TESTS;
export const FETCH_EXPY_TESTS_FAILED = SCOPE + AT.FETCH_EXPY_TESTS_FAILED;
export const FETCH_EXPY_TESTS_SUCCESS = SCOPE + AT.FETCH_EXPY_TESTS_SUCCESS;

export const FETCH_GAMERTAG_GROUPS = SCOPE + AT.FETCH_GAMERTAG_GROUPS;
