export const SIDE_MARGIN = 0;

export const MAIN_NAVBAR_HEIGHT = 40;

export const SUBNAVBAR_HEIGHT = 30;

export const NAVBAR_HEIGHT = MAIN_NAVBAR_HEIGHT + SUBNAVBAR_HEIGHT;

export const FEATURE_SWITCHES_LIST_PREFIX = 'devzone_core/FEATURE_SWITCHES';
