export const OC_SV_PLAYLIST_ID_MAPPING =
  'ONLINE_CONFIGURATION_SESSION_VIEWER_PLAYLIST_ID_MAPPING';

export const OPS4_SPECIFIC_FEATURES_ENABLED = 'OPS4_SPECIFIC_FEATURES_ENABLED';

export const GAMEMODES_CHART_ENABLED = 'GAMEMODES_CHART_ENABLED';

export const ONLINE_CONFIGURATION_GRAPHS_REDIRECT_TO_COREVIZ =
  'ONLINE_CONFIGURATION_GRAPHS_REDIRECT_TO_COREVIZ';

export const MATCHMAKING_RULESETS_ACTIVATE = 'MATCHMAKING_RULESETS_ACTIVATE';

export const ACCOUNTS_USER_TEAMS_DISABLED = 'ACCOUNTS_USER_TEAMS_DISABLED';

export const FEATURE_FLAG_TYPE = {
  USER: 'user',
  PROJECT: 'project',
  TITLE: 'title',
};
