export const LEADERBOARD_RANGES_FETCH = 'security/LEADERBOARD_RANGES_FETCH';
export const LEADERBOARD_RANGES_FETCH_SUCCESS =
  'security/LEADERBOARD_RANGES_FETCH_SUCCESS';

export const LEADERBOARD_RANGE_ADD = 'security/LEADERBOARD_RANGE_ADD';
export const LEADERBOARD_RANGE_ADD_SUCCESS =
  'security/LEADERBOARD_RANGE_ADD_SUCCESS';
export const LEADERBOARD_RANGE_ADD_FAILED =
  'security/LEADERBOARD_RANGE_ADD_FAILED';

export const LEADERBOARD_RANGE_DELETE = 'security/LEADERBOARD_RANGE_DELETE';
export const LEADERBOARD_RANGE_DELETE_SUCCESS =
  'security/LEADERBOARD_RANGE_DELETE_SUCCESS';
