export const MONITORED_USERS_FETCH = 'security/MONITORED_USERS_FETCH';
export const MONITORED_USERS_FETCH_SUCCESS =
  'security/MONITORED_USERS_FETCH_SUCCESS';

export const MONITORED_USERS_ADD = 'security/MONITORED_USERS_ADD';
export const MONITORED_USERS_ADD_SUCCESS =
  'security/MONITORED_USERS_ADD_SUCCESS';
export const MONITORED_USERS_ADD_FAILED = 'security/MONITORED_USERS_ADD_FAILED';

export const MONITORED_USERS_DELETE = 'security/MONITORED_USERS_DELETE';
export const MONITORED_USERS_DELETE_SUCCESS =
  'security/MONITORED_USERS_DELETE_SUCCESS';
