// vim: set syntax=groovy expandtab shiftwidth=4 tabstop=4 softtabstop=4 autoindent smartindent:

def vaultAddr = "https://vault.las.demonware.net:8200"
def vaultCredentialId = "vault-jenkins-approle"
def vaultConfiguration = [engineVersion: 2, vaultUrl: vaultAddr, vaultCredentialId: vaultCredentialId ]

// define the Vault secret path and configure secrets to be assigned to env vars
def vaultSecrets = [
    [
        path: 'secrets/shared/devzone/jenkins', secretValues: [
            [envVar: 'AG_GRID_LICENCE', vaultKey: 'jenkins_ag_grid_licence_key']
        ]
    ]
]

Boolean slackNotificationSent = false
String teamSlackChannel = '#products-devzone-ext'
Boolean deploymentTriggered = false
branchesToNotifyOn = ['master', 'release/*', 'hotfix/*']

pipeline {
    agent { label 'centos7' }
    options {
        buildDiscarder(logRotator(numToKeepStr: '150'))
        timeout(time: 2, unit: 'HOURS')
        timestamps()
    }
    environment {
        DOCKER_TAG = sh(script:'git describe --match "[0-9]*.[0-9]*.[0-9]*"', returnStdout: true).trim()
    }
    stages {
        stage('Builder image') {
            steps {
                sh 'make -f Makefile.testdev image-builder-abtesting DOCKER_TAG=$DOCKER_TAG'
            }
        }
        stage('Code Analysis') {
            steps {
                parallel (
                    "lint-abtesting": {sh 'make -f Makefile.testdev lint-abtesting'},
                    "check-style-abtesting": {sh 'make -f Makefile.testdev check-style-abtesting'}
                )
            }
        }
        stage('Test AB-Testing') {
            steps {
                sh 'make -f Makefile.testdev test-abtesting'
            }
            post {
                always {
                    junit "jest-test-results-abtesting.xml"
                }
            }
        }
        stage('Build DZ Frontend ABTesting Image') {
            steps {
                withVault([configuration: vaultConfiguration, vaultSecrets: vaultSecrets]) {
                    sh 'make -f Makefile.testdev docker-abtesting AUTH_CLIENT=react DOCKER_TAG=$DOCKER_TAG'
                }
                script {
                    currentBuild.description = """${DOCKER_TAG}"""
                }
            }
        }
        stage('Publish') {
            when {
                anyOf {
                    branch 'master'
                    branch 'release/*'
                    branch 'hotfix/*'
                }
            }
            stages {
                stage('Build DZ Frontend ABTesting Image') {
                    steps {
                	withVault([configuration: vaultConfiguration, vaultSecrets: vaultSecrets]) {
                            sh 'make -f Makefile.testdev docker-abtesting AUTH_CLIENT=react DOCKER_TAG=$DOCKER_TAG'
                        }
                    }
                }
                stage('Publish Image') {
                    steps {
                        sh 'echo "On ${BRANCH_NAME}, pushing new image."'
                        sh 'make -f Makefile.testdev docker-push-abtesting DOCKER_TAG=$DOCKER_TAG'
                    }
                }
            }
        }

        stage('Deploy Frontend QA'){
            when {
                branch 'master'
            }
            steps {
                build(
                    job: 'Devzone/Devzone Deploy/master',
                    propagate: true,
                    parameters: [
                        string(name: 'CLUSTER', value: 'i1.kube.demonware.net'),
                        string(name: 'RELEASE', value: 'devzone-abtesting'),
                        string(name: 'DEPLOY', value: 'YES'),
                        string(name: 'COMPONENT', value: 'frontend-abtesting'),
                        string(name: 'TAG', value: env.DOCKER_TAG),
                        string(name: 'NOTIFY_EXTERNAL', value: 'NO')
                    ]
                )
            }
        }
    }
    post {
        success {
            script {
                // This is a hack
                // If the build of the master branch is a success, replace the `currentBuild.description` section
                // of the Jenkins UI with a `release` button.
                currentBuild.description = """<b><i>${DOCKER_TAG}</i></b><br/><form method="post" name="parameters" action="/job/Devzone/job/Devzone%20Deploy/job/master/build?delay=0sec">
    <div name="parameter">
      <input name="name" value="CLUSTER" type="hidden">
      <input name="value" value="s1.kube.demonware.net" type="hidden">
    </div>
    <div name="parameter">
      <input name="name" value="RELEASE" type="hidden">
      <input name="value" value="devzone-abtesting" type="hidden">
    </div>
    <div name="parameter">
      <input name="name" value="DEPLOY" type="hidden">
      <input name="value" value="YES" type="hidden">
    </div>
    <div name="parameter">
      <input name="name" value="COMPONENT" type="hidden">
      <input name="value" value="frontend-abtesting" type="hidden">
    </div>
    <div name="parameter">
      <input name="name" value="TAG" type="hidden">
      <input name="value" value="${DOCKER_TAG}" type="hidden">
    </div>
    <div name="parameter">
      <input name="name" value="NOTIFY_EXTERNAL" type="hidden">
      <input name="value" value="YES" type="hidden">
    </div>
    <input name="statusCode" value="303" type="hidden">
    <button><b>Release to Prod (AB Testing)</b></button>
</form>"""
            }
        }
        changed {
            slackBuildReport(teamSlackChannel, ['branches': branchesToNotifyOn])
            script { slackNotificationSent = true }
        }
        unsuccessful {
            script {
                if (!slackNotificationSent) {
                    slackBuildReport(teamSlackChannel, ['branches': branchesToNotifyOn])
                }
            }
        }
        cleanup {
            cleanupAgent()
        }
    }
}
