export const STORAGE_USER_FILES_FETCH = 'storage/STORAGE_USER_FILES_FETCH';
export const STORAGE_USER_FILES_FETCH_SUCCESS =
  'storage/STORAGE_USER_FILES_FETCH_SUCCESS';

export const STORAGE_USER_FILES_LIST_ITEM_ONCLICK =
  'storage/STORAGE_USER_FILES_LIST_ITEM_ONCLICK';

export const STORAGE_USER_FILES_UPLOAD = 'storage/STORAGE_USER_FILES_UPLOAD';
export const STORAGE_USER_FILES_UPLOAD_SUCCESS =
  'storage/STORAGE_USER_FILES_UPLOAD_SUCCESS';

export const STORAGE_USER_FILES_DELETE = 'storage/STORAGE_USER_FILES_DELETE';
export const STORAGE_USER_FILES_DELETE_SUCCESS =
  'storage/STORAGE_USER_FILES_DELETE_SUCCESS';

export const STORAGE_USER_FILES_DOWNLOAD =
  'storage/STORAGE_USER_FILES_DOWNLOAD';
export const STORAGE_USER_FILES_DOWNLOAD_SUCCESS =
  'storage/STORAGE_USER_FILES_DOWNLOAD_SUCCESS';
