const prefix = 'playpants/SCHEDULE_STORY_DETAILS_FORM';

export const PATCH_SCHEDULE_STORY = `${prefix}.PATCH_SCHEDULE_STORY`;
export const UPLOAD_STORY_SCHEDULE = `${prefix}.UPLOAD_STORY_SCHEDULE`;
export const SET_SELECTED_SCHEDULE = `${prefix}.SET_SELECTED_SCHEDULE`;
