export const ACCOUNTS_TAB_USER_KEYS_FETCH =
  'accounts/ACCOUNTS_TAB_USER_KEYS_FETCH';
export const ACCOUNTS_TAB_USER_KEYS_FETCH_SUCCESS =
  'accounts/ACCOUNTS_TAB_USER_KEYS_FETCH_SUCCESS';

export const ACCOUNTS_TAB_USER_KEYS_ADD = 'accounts/ACCOUNTS_TAB_USER_KEYS_ADD';
export const ACCOUNTS_TAB_USER_KEYS_ADD_SUCCESS =
  'accounts/ACCOUNTS_TAB_USER_KEYS_ADD_SUCCESS';

export const ACCOUNTS_TAB_USER_KEYS_OPEN_MODAL =
  'accounts/ACCOUNTS_TAB_USER_KEYS_OPEN_MODAL';
export const ACCOUNTS_TAB_USER_KEYS_CLOSE_MODAL =
  'accounts/ACCOUNTS_TAB_USER_KEYS_CLOSE_MODAL';
