export const FETCH_FRANCHISE_DATA = 'REPORTING.FETCH_FRANCHISE_DATA';
export const FETCH_FRANCHISE_DATA_SUCCESS =
  'REPORTING.FETCH_FRANCHISE_DATA_SUCCESS';
export const FETCH_FRANCHISE_DATA_FAIL = 'REPORTING.FETCH_FRANCHISE_DATA_FAIL';
