const prefix = 'playpants/SCHEDULE_STORIES_DETAIL_ACTIONS';

export const DELETE_SCHEDULE_STORY = `${prefix}.DELETE_SCHEDULE_STORY`;
export const DELETE_THEN_REDIRECT = `${prefix}.DELETE_THEN_REDIRECT`;
