const prefix = 'playpants/GAMERTAGS_ACCOUNTS_FORM';

export const ASYNC_FETCH_LINKED_ACCOUNTS_LIST = `${prefix}.ASYNC_LINKED_ACCOUNTS_LIST_FETCH`;
export const ASYNC_FETCH_LINKED_ACCOUNTS_LIST_SUCCESS = `${prefix}.ASYNC_LINKED_ACCOUNTS_LIST_FETCH_SUCCESS`;
export const ASYNC_FETCH_LINKED_ACCOUNTS_LIST_FAILED = `${prefix}.ASYNC_LINKED_ACCOUNTS_LIST_FETCH_FAILED`;

export const ASYNC_FETCH_ACCOUNTS_GROUP = `${prefix}.ASYNC_ACCOUNTS_GROUP_FETCH`;
export const ASYNC_FETCH_ACCOUNTS_GROUP_SUCCESS = `${prefix}.ASYNC_ACCOUNTS_GROUP_FETCH_SUCCESS`;
export const ASYNC_FETCH_ACCOUNTS_GROUP_FAILED = `${prefix}.ASYNC_ACCOUNTS_GROUP_FETCH_FAILED`;
