const prefix = 'playpants/RULES';

export const FETCH_CLIENT_RULES_SCHEMA = `${prefix}.FETCH_CLIENT_RULES_SCHEMA`;
export const FETCH_CLIENT_RULES_SCHEMA_SUCCESS = `${prefix}.FETCH_CLIENT_RULES_SCHEMA_SUCCESS`;
export const CLEAR_CLIENT_RULES_SCHEMA = `${prefix}.CLEAR_CLIENT_RULES_SCHEMA`;
export const UPDATE_PROJECT_SETTINGS = `${prefix}.UPDATE_PROJECT_SETTINGS`;
