export const ANTICHEAT_STATISTICS_CHANGE_USER_ID =
  'security/ANTICHEAT_STATISTICS_CHANGE_USER_ID';
export const ANTICHEAT_STATISTICS_CHANGE_CHALLENGE_ID =
  'security/ANTICHEAT_STATISTICS_CHANGE_CHALLENGE_ID';
export const ANTICHEAT_STATISTICS_CHANGE_DATE =
  'security/ANTICHEAT_STATISTICS_CHANGE_DATE';
