const prefix = 'playpants/ACTIVITIES.PYSCRIPT';

export const FETCH_PYSCRIPT_SCHEMAS = `${prefix}.SCHEMAS`;
export const FETCH_PYSCRIPT_SCHEMAS_SUCCESS = `${prefix}.SCHEMAS_FETCH_SUCCESS`;

export const UPDATE_SCHEMA_MODEL = `${prefix}.SCHEMA_MODEL`;
export const UPDATE_SCHEMA_MODEL_SUCCESS = `${prefix}.SCHEMA_MODEL_UPDATE_SUCCESS`;
export const UPDATE_SCHEMA_MODEL_FAILED = `${prefix}.SCHEMA_MODEL_UPDATE_FAILED`;
