export const USER_CONTEXT_STORAGE_DETAILS_DELETE_FILE =
  'storage/USER_CONTEXT_STORAGE_DETAILS_DELETE_FILE';
export const USER_CONTEXT_STORAGE_DETAILS_DELETE_FILE_SUCCESS =
  'storage/USER_CONTEXT_STORAGE_DETAILS_DELETE_FILE_SUCCESS';

export const USER_CONTEXT_STORAGE_DETAILS_FILE_DOWNLOAD =
  'storage/USER_CONTEXT_STORAGE_DETAILS_FILE_DOWNLOAD';
