export const TOURNAMENT_SESSION_VIEWER_TOURNAMENTS_FETCH =
  'session-viewer/TOURNAMENT_SESSION_VIEWER_TOURNAMENTS_FETCH';
export const TOURNAMENT_SESSION_VIEWER_TOURNAMENTS_FETCH_SUCCESS =
  'session-viewer/TOURNAMENT_SESSION_VIEWER_TOURNAMENTS_FETCH_SUCCESS';

export const TOURNAMENT_SESSION_VIEWER_LOBBIES_FETCH =
  'session-viewer/TOURNAMENT_SESSION_VIEWER_LOBBIES_FETCH';

export const TOURNAMENT_SESSION_VIEWER_LOBBIES_FETCH_SUCCESS =
  'session-viewer/TOURNAMENT_SESSION_VIEWER_LOBBIES_FETCH_SUCCESS';

export const TOURNAMENT_SESSION_VIEWER_ACCOUNTS_FETCH =
  'session-viewer/TOURNAMENT_SESSION_VIEWER_ACCOUNTS_FETCH';

export const TOURNAMENT_SESSION_VIEWER_ACCOUNTS_FETCH_SUCCESS =
  'session-viewer/TOURNAMENT_SESSION_VIEWER_ACCOUNTS_FETCH_SUCCESS';
