export const CHALLENGES_FETCH = 'security/CHALLENGES_FETCH';
export const CHALLENGES_FETCH_SUCCESS = 'security/CHALLENGES_FETCH_SUCCESS';
export const CHALLENGES_FETCH_FAILED = 'security/CHALLENGES_FETCH_FAILED';

export const CHALLENGE_ADD = 'security/CHALLENGE_ADD';
export const CHALLENGE_ADD_SUCCESS = 'security/CHALLENGE_ADD_SUCCESS';
export const CHALLENGE_ADD_FAILED = 'security/CHALLENGE_ADD_FAILED';

export const CHALLENGE_EDIT = 'security/CHALLENGE_EDIT';
export const CHALLENGE_EDIT_SUCCESS = 'security/CHALLENGE_EDIT_SUCCESS';
export const CHALLENGES_SET_CURRENT = 'security/CHALLENGES_SET_CURRENT';
