export const REVISION_HISTORY_FETCH = 'security/REVISION_HISTORY_FETCH';
export const REVISION_HISTORY_FETCH_SUCCESS =
  'security/REVISION_HISTORY_FETCH_SUCCESS';

export const REVISION_HISTORY_REVERT = 'security/REVISION_HISTORY_REVERT';
export const REVISION_HISTORY_REVERT_SUCCESS =
  'security/REVISION_HISTORY_REVERT_SUCCESS';
