export const PUBLISHER_STORAGE_FETCH = 'storage/PUBLISHER_STORAGE_FETCH';
export const PUBLISHER_STORAGE_FETCH_SUCCESS =
  'storage/PUBLISHER_STORAGE_FETCH_SUCCESS';

export const PUBLISHER_STORAGE_LIST_ITEM_ONCLICK =
  'storage/PUBLISHER_STORAGE_LIST_ITEM_ONCLICK';

export const PUBLISHER_STORAGE_FILES_UPLOAD =
  'storage/PUBLISHER_STORAGE_FILES_UPLOAD';
export const PUBLISHER_STORAGE_FILES_UPLOAD_SUCCESS =
  'storage/PUBLISHER_STORAGE_FILES_UPLOAD_SUCCESS';

export const PUBLISHER_STORAGE_FILES_BULK_DELETE =
  'storage/PUBLISHER_STORAGE_FILES_BULK_DELETE';
export const PUBLISHER_STORAGE_FILES_BULK_DELETE_SUCCESS =
  'storage/PUBLISHER_STORAGE_FILES_BULK_DELETE_SUCCESS';

export const PUBLISHER_STORAGE_FILES_BULK_DOWNLOAD =
  'storage/PUBLISHER_STORAGE_FILES_BULK_DOWNLOAD';
