export const PUBLISHER_STORAGE_DETAILS_DELETE_FILE =
  'storage/PUBLISHER_STORAGE_DETAILS_DELETE_FILE';
export const PUBLISHER_STORAGE_DETAILS_DELETE_FILE_SUCCESS =
  'storage/PUBLISHER_STORAGE_DETAILS_DELETE_FILE_SUCCESS';

export const PUBLISHER_STORAGE_DETAILS_FILE_DOWNLOAD =
  'storage/PUBLISHER_STORAGE_DETAILS_FILE_DOWNLOAD';
