export const COLUMNS = [
  {
    field: 'testStatus',
    rowGroup: true,
    hide: true,
    width: 220,
  },
  {
    headerName: 'ID',
    field: 'id',
    cellStyle: { fontWeight: 'bold' },
    width: 250,
  },
  {
    headerName: 'Test Name',
    field: 'name',
    cellRenderer: 'testNameRenderer',
    width: 250,
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Title',
    field: 'title',
    width: 150,
  },
  {
    headerName: 'Platform',
    field: 'platform',
    width: 140,
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Env',
    field: 'environment',
    cellStyle: params =>
      params.value === 'live' ? { backgroundColor: '#cfeae7' } : {},
    width: 100,
  },
  {
    headerName: 'Source',
    field: 'source',
    maxWidth: 160,
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Target',
    field: 'target',
    width: 130,
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Category',
    field: 'category',
    width: 160,
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Status',
    field: 'status',
    cellRenderer: 'statusTableFieldRenderer',
    width: 170,
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Test Period From',
    field: 'testPeriodStart',
    width: 220,
    valueFormatter: params => params.context.formatDate(params.value),
  },
  {
    headerName: 'Test Period To',
    field: 'testPeriodEnd',
    width: 200,
    valueFormatter: params => params.context.formatDate(params.value),
    autoHeight: true,
    cellStyle: { 'white-space': 'normal', 'word-wrap': 'break-word' },
  },
  {
    headerName: 'Actions',
    cellRenderer: 'actionsRenderer',
    field: 'action',
    width: 300,
    pinned: 'right',
  },
];
