export const LOBBIES_FETCH_THUNDERPANTS_LINK =
  'LOBBIES_FETCH_THUNDERPANTS_LINK';
export const LOBBIES_FETCH_THUNDERPANTS_LINK_FAILED =
  'LOBBIES_FETCH_THUNDERPANTS_LINK_FAILED';
export const LOBBIES_FETCH_THUNDERPANTS_LINK_SUCCESS =
  'LOBBIES_FETCH_THUNDERPANTS_LINK_SUCCESS';
