export const ACCOUNTS_TAB_USER_FRIENDS_FETCH =
  'accounts/ACCOUNTS_TAB_USER_FRIENDS_FETCH';
export const ACCOUNTS_TAB_USER_FRIENDS_FETCH_SUCCESS =
  'accounts/ACCOUNTS_TAB_USER_FRIENDS_FETCH_SUCCESS';
