export const MM_SERVER_LIST_FETCH = 'MM_SERVER_LIST_FETCH';
export const MM_SERVER_LIST_FETCH_SUCCESS = 'MM_SERVER_LIST_FETCH_SUCCESS';
export const MM_SERVER_LIST_FETCH_FAILED = 'MM_SERVER_LIST_FETCH_FAILED';
