export const SECURITY_CHALLENGE_LOGS_FETCH =
  'security/SECURITY_CHALLENGE_LOGS_FETCH';
export const SECURITY_CHALLENGE_LOGS_FETCH_SUCCESS =
  'security/SECURITY_CHALLENGE_LOGS_FETCH_SUCCESS';

export const SECURITY_CHALLENGE_LOGS_LIST_ITEM_ONCLICK =
  'security/SECURITY_CHALLENGE_LOGS_LIST_ITEM_ONCLICK';
