const PREFIX = 'object-store/';

export const OBJECTS_DELETE = `${PREFIX}OBJECTS_DELETE`;
export const OBJECTS_DELETE_SUCCESS = `${PREFIX}OBJECTS_DELETE_SUCCESS`;

export const OBJECT_DOWNLOAD = `${PREFIX}OBJECT_DOWNLOAD`;
export const OBJECT_DOWNLOAD_SUCCESS = `${PREFIX}OBJECT_DOWNLOAD_SUCCESS`;

export const OBJECT_PROMOTE = `${PREFIX}OBJECT_PROMOTE`;

export const UPLOAD_OBJECT = `${PREFIX}UPLOAD_OBJECT`;

export const PROPAGATE_OBJECTS = 'PROPAGATE_OBJECTS';

export const START_UPLOAD_PROGRESS = `${PREFIX}START_UPLOAD_PROGRESS`;
export const INCREMENT_UPLOAD_PROGRESS = `${PREFIX}INCREMENT_UPLOAD_PROGRESS`;
export const STOP_UPLOAD_PROGRESS = `${PREFIX}STOP_UPLOAD_PROGRESS`;
export const FAIL_UPLOAD_PROGRESS = `${PREFIX}FAIL_UPLOAD_PROGRESS`;
