export const SESSION_VIEWER_LOBBIES_FETCH =
  'session-viewer/SESSION_VIEWER_LOBBIES_FETCH';
export const SESSION_VIEWER_LOBBIES_FETCH_SUCCESS =
  'session-viewer/SESSION_VIEWER_LOBBIES_FETCH_SUCCESS';
export const SESSION_VIEWER_PLAYLISTS_FETCH =
  'session-viewer/SESSION_VIEWER_PLAYLISTS_FETCH';
export const SESSION_VIEWER_PLAYLISTS_FETCH_SUCCESS =
  'session-viewer/SESSION_VIEWER_PLAYLISTS_FETCH_SUCCESS';
