const prefix = 'playpants/SCHEDULE_STORIES';

export const SEARCH_SCHEDULE_STORIES = `${prefix}.SEARCH`;
export const SET_SELECTED_SCHEDULE_STORY = `${prefix}.SET_SELECTED_SCHEDULE_STORY`;

export const FETCH_SCHEDULE_STORY_THEN_SELECT = `${prefix}.FETCH_SCHEDULE_STORY_THEN_SELECT`;
export const FETCH_SCHEDULE_STORY_THEN_SELECT_SUCCESS = `${FETCH_SCHEDULE_STORY_THEN_SELECT}_SUCCESS`;
export const FETCH_SCHEDULE_STORY_THEN_SELECT_FAILED = `${FETCH_SCHEDULE_STORY_THEN_SELECT}_FAILED`;

export const RESET_SELECTED_SCHEDULE_STORY = `${prefix}.RESET_SELECTED_SCHEDULE_STORY`;
export const RESET_SCHEDULE_STORIES = `${prefix}.RESET_SCHEDULE_STORIES`;

export const START_POLL_SCHEDULES = `${prefix}.START_POLL_SCHEDULES`;
export const STOP_POLL_SCHEDULES = `${prefix}.STOP_POLL_SCHEDULES`;

export const STORE_SELECTED_SCHEDULE_STORY = `${prefix}.STORE_SELECTED_SCHEDULE_STORY`;
export const STORE_SELECTED_SCHEDULE_STORY_SUCCESS = `${prefix}.STORE_SELECTED_SCHEDULE_STORY_SUCCESS`;
export const STORE_SELECTED_SCHEDULE_STORY_FAILED = `${prefix}.STORE_SELECTED_SCHEDULE_STORY_FAILED`;
