export const MAX_ICONS_WITHOUT_ACTION_MENU = 4;
export const MAX_ICONS_OUTSIDE_ACTION_MENU = 3;
export const REQUEST_APPROVAL_MODAL_ID = 'REQUEST_APPROVAL_MODAL';
export const PUBLISH_NOW_MODAL_ID = 'PUBLISH_NOW_MODAL';
export const RETRY_PUBLISH_MODAL_ID = 'RETRY_PUBLISH_MODAL';
