const prefix = 'playpants/SCHEDULE_COMPONENT';

export const FETCH_APPEND = `${prefix}.FETCH_APPEND`;
export const FETCH_EVENT_BY_SOURCE_EVENT_ID = `${prefix}.EVENT_BY_SOURCE_EVENT_ID`;
export const RESET = `${prefix}.RESET`;
export const CREATE_EVENT = `${prefix}.CREATE_EVENT`;
export const CREATE_EVENT_FAILED = `${prefix}.CREATE_EVENT_FAILED`;
export const CREATE_EVENT_SUCCESS = `${prefix}.CREATE_EVENT_SUCCESS`;

export const SET_SELECTED_EVENT_TEMPLATE = `${prefix}.SET_SELECTED_EVENT_TEMPLATE`;
export const UPDATE_CREATE_FORM_DEFAULT_DATE = `${prefix}.UPDATE_CREATE_FORM_DEFAULT_DATE`;

export const STORE_THEN_OPEN_EVENT_DETAIL_MODAL = `${prefix}.STORE_THEN_OPEN_EVENT_DETAIL_MODAL`;
export const STORE_EVENT = `${prefix}.STORE_EVENT`;
export const STORE_THEN_OPEN_AB_TEST_DETAIL_MODAL = `${prefix}.STORE_THEN_OPEN_AB_TEST_DETAIL_MODAL`;
export const STORE_AB_TEST = `${prefix}.STORE_AB_TEST`;
export const STORE_THEN_OPEN_EXPY_TEST_DETAIL_MODAL = `${prefix}.STORE_THEN_OPEN_EXPY_TEST_DETAIL_MODAL`;
export const STORE_EXPY_TEST = `${prefix}.STORE_EXPY_TEST`;
export const STORE_THEN_OPEN_DEMONWARE_DETAIL_MODAL = `${prefix}.STORE_THEN_OPEN_DEMONWARE_DETAIL_MODAL`;
export const STORE_DEMONWARE_EVENT = `${prefix}.STORE_DEMONWARE_EVENT`;
export const STORE_THEN_OPEN_EXTERNAL_DETAIL_MODAL = `${prefix}.STORE_THEN_OPEN_EXTERNAL_DETAIL_MODAL`;
export const STORE_EXTERNAL_EVENT = `${prefix}.STORE_EXTERNAL_EVENT`;

export const FETCH_EVENT_DETAILS = `${prefix}.FETCH_EVENT_DETAILS`;
export const FETCH_EVENT_DETAILS_FAILED = `${prefix}.FETCH_EVENT_DETAILS_FAILED`;
export const FETCH_EVENT_DETAILS_SUCCESS = `${prefix}.FETCH_EVENT_DETAILS_SUCCESS`;
export const RESET_EVENT_FETCH_DETAILS = `${prefix}.RESET_EVENT_FETCH_DETAILS`;

export const EXPORT_EVENTS = `${prefix}.EXPORT_EVENTS`;

export const UPDATE_EVENT = `${prefix}.EVENT_UPDATE`;
export const UPDATE_EVENT_SUCCESS = `${prefix}.EVENT_UPDATE_SUCCESS`;
export const UPDATE_EVENT_FAILED = `${prefix}.EVENT_UPDATE_UPDATE_FAILED`;

export const SET_FILTER_PROPS_DISABLED = `${prefix}.SET_FILTER_PROPS_DISABLED`;
export const CHECK_STORIES_FILTER_DISABLED = `${prefix}.CHECK_STORIES_FILTER_DISABLED`;
export const CHECK_STORIES_FILTER_DISABLED_SUCCESS = `${prefix}.CHECK_STORIES_FILTER_DISABLED_SUCCESS`;
export const CHECK_STORIES_FILTER_DISABLED_FAILED = `${prefix}.CHECK_STORIES_FILTER_DISABLED_FAILED`;

/**
 * Scoped actions to be handled by scheduleEventsReducerFor creator
 */

export const FETCH_EVENT_MANAGER_EVENTS = `.EVENT_MANAGER_EVENTS_FETCH`;
export const FETCH_EVENT_MANAGER_EVENTS_FAILED = `${FETCH_EVENT_MANAGER_EVENTS}_FAILED`;
export const FETCH_EVENT_MANAGER_EVENTS_SUCCESS = `${FETCH_EVENT_MANAGER_EVENTS}_SUCCESS`;

export const FETCH_EXTERNAL_EVENTS = `.EXTERNAL_EVENTS_FETCH`;
export const FETCH_EXTERNAL_EVENTS_FAILED = `${FETCH_EXTERNAL_EVENTS}_FAILED`;
export const FETCH_EXTERNAL_EVENTS_SUCCESS = `${FETCH_EXTERNAL_EVENTS}_SUCCESS`;

export const FETCH_INFORMATIONAL_EVENTS = `.INFORMATIONAL_EVENTS_FETCH`;
export const FETCH_INFORMATIONAL_EVENTS_FAILED = `${FETCH_INFORMATIONAL_EVENTS}_FAILED`;
export const FETCH_INFORMATIONAL_EVENTS_SUCCESS = `${FETCH_INFORMATIONAL_EVENTS}_SUCCESS`;

export const FETCH_DEMONWARE_EVENTS = `.DEMONWARE_EVENTS_FETCH`;
export const FETCH_DEMONWARE_EVENTS_FAILED = `${FETCH_DEMONWARE_EVENTS}_FAILED`;
export const FETCH_DEMONWARE_EVENTS_SUCCESS = `${FETCH_DEMONWARE_EVENTS}_SUCCESS`;

export const FETCH_AB_TESTS = `.AB_TESTS_FETCH`;
export const FETCH_AB_TESTS_FAILED = `${FETCH_AB_TESTS}_FAILED`;
export const FETCH_AB_TESTS_SUCCESS = `${FETCH_AB_TESTS}_SUCCESS`;

export const FETCH_EXPY_TESTS = `.EXPY_TESTS_FETCH`;
export const FETCH_EXPY_TESTS_FAILED = `${FETCH_EXPY_TESTS}_FAILED`;
export const FETCH_EXPY_TESTS_SUCCESS = `${FETCH_EXPY_TESTS}_SUCCESS`;

export const FETCH_GAMERTAG_GROUPS = `.GAMERTAG_GROUPS`;
