export const ANTICHEAT_STATISTICS_FETCH =
  'security/ANTICHEAT_STATISTICS_BY_CHALLENGE_FETCH';
export const ANTICHEAT_STATISTICS_FETCH_SUCCESS =
  'security/ANTICHEAT_STATISTICS_BY_CHALLENGE_FETCH_SUCCESS';
