export const COLUMNS = [
  {
    title: 'ChallengeId',
    dataIndex: 'challengeId',
    key: 'challengeId',
    width: '13%',
  },
  {
    title: '#Failures',
    dataIndex: 'failures',
    key: 'failures',
    type: 'number',
    width: '13%',
  },
  {
    title: '(incl. #Unanswered)',
    dataIndex: 'unanswered',
    key: 'unanswered',
    type: 'number',
    width: '17%',
  },
  {
    title: '(incl. #Punishments)',
    dataIndex: 'punishments',
    key: 'punishments',
    type: 'number',
    width: '18%',
  },
  {
    title: 'Correct',
    dataIndex: 'correct',
    key: 'correct',
    type: 'number',
    width: '13%',
  },
  {
    title: 'Unexpected',
    dataIndex: 'unexpected',
    key: 'unexpected',
    type: 'number',
    width: '13%',
  },
  {
    title: '%Correct',
    dataIndex: 'percentCorrect',
    key: 'percentCorrect',
    type: 'number',
    width: '13%',
  },
];
