const prefix = 'playpants/RESPONSIBILITY_USER_GROUPS_FORM';
export const ASYNC_FETCH_GROUP_LIST = `${prefix}.ASYNC_GROUP_LIST_FETCH`;
export const ASYNC_FETCH_GROUP_LIST_SUCCESS = `${prefix}.ASYNC_GROUP_LIST_FETCH_SUCCESS`;
export const ASYNC_FETCH_GROUP_LIST_FAILED = `${prefix}.ASYNC_GROUP_LIST_FETCH_FAILED`;
