const prefix = 'playpants/RESPONSIBILITIES';

export const FETCH_GROUP_LIST = `${prefix}.GROUP_LIST`;
export const FILTER_GROUPS = `${prefix}.FILTER_GROUPS`;

export const FETCH_RESPONSIBILITY_OPTIONS = `${prefix}.RESPONSIBILITY_OPTIONS`;
export const FETCH_RESPONSIBILITY_GROUPS = `${prefix}.RESPONSIBILITY_GROUPS`;

export const UPDATE_RESPONSIBILITIES = `${prefix}.UPDATE_RESPONSIBILITIES`;
export const UPDATE_RESPONSIBILITIES_SUCCESS = `${prefix}.UPDATE_RESPONSIBILITIES_SUCCESS`;
export const UPDATE_RESPONSIBILITIES_FAILED = `${prefix}.UPDATE_RESPONSIBILITIES_FAILED`;

export const CREATE_RESPONSIBILITY_GROUPS = `${prefix}.CREATE_RESPONSIBILITY_GROUPS`;
export const CREATE_RESPONSIBILITY_GROUPS_SUCCESS = `${prefix}.CREATE_RESPONSIBILITY_GROUPS_SUCCESS`;
export const CREATE_RESPONSIBILITY_GROUPS_FAILED = `${prefix}.CREATE_RESPONSIBILITY_GROUPS_FAILED`;
