export const USER_ACHIEVEMENTS_FETCH = 'achievements/USER_ACHIEVEMENTS_FETCH';
export const USER_ACHIEVEMENTS_FETCH_SUCCESS =
  'achievements/USER_ACHIEVEMENTS_FETCH_SUCCESS';

/* DELETE */

export const USER_ACHIEVEMENTS_DELETE = 'achievements/USER_ACHIEVEMENTS_DELETE';
export const USER_ACHIEVEMENTS_DELETE_SUCCESS =
  'achievements/USER_ACHIEVEMENTS_DELETE_SUCCESS';

export const USER_ACHIEVEMENTS_OPEN_DELETE_MODAL =
  'achievements/USER_ACHIEVEMENTS_OPEN_DELETE_MODAL';
export const USER_ACHIEVEMENTS_CLOSE_DELETE_MODAL =
  'achievements/USER_ACHIEVEMENTS_CLOSE_DELETE_MODAL';
