export const STORAGE_GROUP_MEMBERS_FETCH =
  'storage/STORAGE_GROUP_MEMBERS_FETCH';
export const STORAGE_GROUP_MEMBERS_FETCH_SUCCESS =
  'storage/STORAGE_GROUP_MEMBERS_FETCH_SUCCESS';

export const STORAGE_GROUP_MEMBERS_LIST_ITEM_ONCLICK =
  'storage/STORAGE_GROUP_MEMBERS_LIST_ITEM_ONCLICK';
export const STORAGE_GROUP_MEMBERS_FETCH_DETAILS_SUCCESS =
  'storage/STORAGE_GROUP_MEMBERS_FETCH_DETAILS_SUCCESS';

export const STORAGE_GROUP_MEMBERS_OPEN_ADD_MODAL =
  'storage/STORAGE_GROUP_MEMBERS_OPEN_ADD_MODAL';
export const STORAGE_GROUP_MEMBERS_CLOSE_ADD_MODAL =
  'storage/STORAGE_GROUP_MEMBERS_CLOSE_ADD_MODAL';
export const STORAGE_GROUP_MEMBERS_OPEN_ADD_MEMBERS_MODAL =
  'storage/STORAGE_GROUP_MEMBERS_OPEN_ADD_MEMBERS_MODAL';
export const STORAGE_GROUP_MEMBERS_CLOSE_ADD_MEMBERS_MODAL =
  'storage/STORAGE_GROUP_MEMBERS_CLOSE_ADD_MEMBERS_MODAL';
export const STORAGE_GROUP_MEMBERS_ADD = 'storage/STORAGE_GROUP_MEMBERS_ADD';
export const STORAGE_GROUP_MEMBERS_ADD_SUCCESS =
  'storage/STORAGE_GROUP_MEMBERS_ADD_SUCCESS';

export const STORAGE_GROUP_MEMBERS_DELETE =
  'storage/STORAGE_GROUP_MEMBERS_DELETE';
export const STORAGE_GROUP_MEMBERS_DELETE_SUCCESS =
  'storage/STORAGE_GROUP_MEMBERS_DELETE_SUCCESS';

export const STORAGE_GROUP_MEMBERS_DOWNLOAD =
  'storage/STORAGE_GROUP_MEMBERS_DOWNLOAD';
export const STORAGE_GROUP_MEMBERS_DOWNLOAD_SUCCESS =
  'storage/STORAGE_GROUP_MEMBERS_DOWNLOAD_SUCCESS';

export const STORAGE_GROUP_MEMBERS_FETCH_GROUP_DETAILS =
  'storage/STORAGE_GROUP_MEMBERS_FETCH_GROUP_DETAILS';
export const STORAGE_GROUP_MEMBERS_FETCH_GROUP_DETAILS_SUCCESS =
  'storage/STORAGE_GROUP_MEMBERS_FETCH_GROUP_DETAILS_SUCCESS';
