export const FETCH_POOLED_OBJECT_TAGS = 'FETCH_POOLED_OBJECT_TAGS';
export const POOLED_OBJECT_SEARCH = 'POOLED_OBJECT_SEARCH';
export const POOLED_OBJECT_SEARCH_SUCCESS = 'POOLED_OBJECT_SEARCH_SUCCESS';
export const POOLED_OBJECT_SEARCH_FAILED = 'POOLED_OBJECT_SEARCH_FAILED';
