export const FETCH = 'MATCHMAKING-RSDOCS.FETCH';
export const FETCH_SUCCESS = 'MATCHMAKING-RSDOCS.FETCH_SUCCESS';
export const FETCH_FAILED = 'MATCHMAKING-RSDOCS.FETCH_FAILED';

export const FETCH_DETAILS = 'MATCHMAKING-RSDOCS.FETCH_DETAILS';
export const FETCH_DETAILS_SUCCESS = 'MATCHMAKING-RSDOCS.FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILED = 'MATCHMAKING-RSDOCS.FETCH_DETAILS_FAILED';

export const ACTIVATE = 'MATCHMAKING-RSDOCS.ACTIVATE';
export const ACTIVATE_SUCCESS = 'MATCHMAKING-RSDOCS.ACTIVATE_SUCCESS';

export const UPLOAD_RULESET = 'MATCHMAKING-RSDOCS.UPLOAD_RULESET';
export const UPLOAD_RULESET_SUCCESS =
  'MATCHMAKING-RSDOCS.UPLOAD_RULESET_SUCCESS';
export const UPLOAD_RULESET_FAILED = 'MATCHMAKING-RSDOCS.UPLOAD_RULESET_FAILED';

export const LIST_ITEM_ONCLICK = 'MATCHMAKING-RSDOCS.LIST_ITEM_ONCLICK';
