export const STORAGE_QUOTA_ALLOWANCE_FETCH =
  'storage/STORAGE_QUOTA_ALLOWANCE_FETCH';
export const STORAGE_QUOTA_ALLOWANCE_FETCH_SUCCESS =
  'storage/STORAGE_QUOTA_ALLOWANCE_FETCH_SUCCESS';

export const STORAGE_QUOTA_ALLOWANCE_LIST_ITEM_ONCLICK =
  'storage/STORAGE_QUOTA_ALLOWANCE_LIST_ITEM_ONCLICK';

export const STORAGE_QUOTA_ALLOWANCE_ADD_MODAL_OPEN =
  'storage/STORAGE_QUOTA_ALLOWANCE_ADD_MODAL_OPEN';
export const STORAGE_QUOTA_ALLOWANCE_ADD_MODAL_CLOSE =
  'storage/STORAGE_QUOTA_ALLOWANCE_ADD_MODAL_CLOSE';
export const STORAGE_QUOTA_ALLOWANCE_ADD =
  'storage/STORAGE_QUOTA_ALLOWANCE_ADD';
export const STORAGE_QUOTA_ALLOWANCE_ADD_SUCCESS =
  'storage/STORAGE_QUOTA_ALLOWANCE_ADD_SUCCESS';
