export const SERVER_LOGS_FETCH = 'debugging/SERVER_LOGS_FETCH';

export const SERVER_LOGS_FETCH_DETAILS = 'debugging/SERVER_LOGS_FETCH_DETAILS';
export const SERVER_LOGS_FETCH_DETAILS_SUCCESS =
  'debugging/SERVER_LOGS_FETCH_DETAILS_SUCCESS';

export const SERVER_LOGS_EXPANDED_FETCH =
  'debugging/SERVER_LOGS_EXPANDED_FETCH';

export const SERVER_LOGS_EXPANDED_FETCH_SUCCESS =
  'debugging/SERVER_LOGS_EXPANDED_FETCH_SUCCESS';

export const SERVER_LOGS_EXPORT = 'debugging/SERVER_LOGS_EXPORT';
export const SERVER_LOGS_EXPORT_SUCCESS =
  'debugging/SERVER_LOGS_EXPORT_SUCCESS';
export const SERVER_LOGS_EXPORT_FAILED = 'debugging/SERVER_LOGS_EXPORT_FAILED';
