export const ACCOUNTS_FETCH = 'accounts/ACCOUNTS_FETCH';
export const ACCOUNTS_FETCH_SUCCESS = 'accounts/ACCOUNTS_FETCH_SUCCESS';

export const ACCOUNTS_LIST_ITEM_ONCLICK = 'accounts/ACCOUNTS_LIST_ITEM_ONCLICK';
export const ACCOUNTS_EXPORT = 'accounts/ACCOUNTS_EXPORT';

export const ACCOUNTS_UPDATE_SELECTED_ACCOUNT =
  'accounts/ACCOUNTS_UPDATE_SELECTED_ACCOUNT';
