export const ACCOUNTS_TAB_USER_DETAILS_FETCH =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_FETCH';
export const ACCOUNTS_TAB_USER_DETAILS_FETCH_SUCCESS =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_FETCH_SUCCESS';
export const ACCOUNTS_TAB_USER_DETAILS_UPDATE_PROFILE =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_UPDATE_PROFILE';
export const ACCOUNTS_TAB_USER_DETAILS_UPDATE_PROFILE_SUCCESS =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_UPDATE_PROFILE_SUCCESS';
export const ACCOUNTS_TAB_USER_DETAILS_DELETE_PROFILE =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_DELETE_PROFILE';
export const ACCOUNTS_TAB_USER_DETAILS_CHANGE_REPUTATION =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_CHANGE_REPUTATION';
export const ACCOUNTS_TAB_USER_DETAILS_CHANGE_REPUTATION_SUCCESS =
  'accounts/ACCOUNTS_TAB_USER_DETAILS_CHANGE_REPUTATION_SUCCESS';
