export const ABTESTING_DESIGN = 'ABTESTING.DESIGN';
export const ABTESTING_DELETE_SEGMENT = 'ABTESTING.DELETE_SEGMENT';
export const TA_ONLINE_ENABLED = 'TA_ONLINE_ENABLED';
export const MA_ONLINE_ENABLED = 'MA_ONLINE_ENABLED';
export const FORGE_ENABLED = 'FORGE_ENABLED';
export const SLEDGE_ENABLED = 'SLEDGE_ENABLED';
export const RAVEN_ENABLED = 'RAVEN_ENABLED';
export const CLANS_ENABLED = 'CLANS.VIEW_ENABLED';
export const PLAYER_TOOLING_ENABLED = 'PLAYER.VIEW_ENABLED';
export const PLAYER_VIEW_V2_ENABLED = 'PLAYER.V2_VIEW_ENABLED';
export const SHOW_PLAYER_UNO_PII = 'PLAYER.SHOW_UNO_PII';
export const SHOW_PLAYER_TITLE_DETAILS = 'PLAYER.SHOW_TITLE_ACTIVITY_DETAILS';
export const SHOW_PLAYER_BANS = 'PLAYER.SHOW_PLAYER_BANS';
export const DISPLAY_PLAYER_LEADERBOARDS = 'PLAYER.DISPLAY_LEADERBOARDS';
export const DISPLAY_PLAYER_ABTESTING = 'PLAYER.DISPLAY_ABTESTING';
export const DISPLAY_PLAYER_TITLE_SUMMARY = 'PLAYER.DISPLAY_TITLE_SUMMARY';
export const AUDIT_LOGS_ENABLED = 'AUDIT_LOGS_ENABLED';
export const MAINTENANCE_ACTIVE = 'MAINTENANCE_ACTIVE';
export const NOTIFICATIONS_CRITICAL_EVENTS = 'NOTIFICATIONS_CRITICAL_EVENTS';
export const ENABLE_PLAYER_ID_SEARCH = 'ENABLE_PLAYER_ID_SEARCH';
export const GROUPS_UPLOAD_PLAYERS = 'GROUPS_UPLOAD_PLAYERS';
export const LOOT_GEN_ENABLED = 'LOOT_GEN_ENABLED';
export const PLAYER_INVENTORY_ENABLED = 'PLAYER_INVENTORY_ENABLED';
export const CLAN_INVENTORY_ENABLED = 'CLAN_INVENTORY_ENABLED';
export const PLAYER_ACHIEVEMENTS_ENABLED = 'PLAYER_ACHIEVEMENTS_ENABLED';
export const CLAN_ACHIEVEMENTS_ENABLED = 'CLAN_ACHIEVEMENTS_ENABLED';
export const PUBLISHER_VARIABLES_PROPAGATE_VARIABLE_SET =
  'PUBLISHER_VARIABLES.PROPAGATE_VARIABLE_SET';
export const REPORTING_PLATFORMS_USE_3_COLUMNS =
  'REPORTING_PLATFORMS_USE_3_COLUMNS';
export const REPORTING_UNIT_ENABLED = 'REPORTING_UNIT_ENABLED';
export const SESSION_VIEWER_USE_AGGRID = 'SESSION_VIEWER_USE_AGGRID';
export const TOURNAMENT_SESSION_VIEWER = 'TOURNAMENT_SESSION_VIEWER';
export const OBJECT_STORE_PROPAGATE_OBJECTS = 'OBJECT_STORE.PROPAGATE_OBJECTS';
export const OBJECT_STORE_STATS = 'OBJECT_STORE_STATS';
export const OBJECT_STORE_POOLED_OBJECTS = 'OBJECT_STORE.POOLED_OBJECTS';
export const OBJECT_STORE_CONTENT_URL_ENABLED =
  'OBJECT_STORE.CONTENT_URL_ENABLED';
export const OBJECT_STORE_BROWSER_DOWNLOAD_CONTENT_URL_ENABLED =
  'OBJECT_STORE.BROWSER_DOWNLOAD_CONTENT_URL_ENABLED';
export const PUBLISHER_OBJECTS_MULTI_DOWNLOAD =
  'PUBLISHER_OBJECTS_MULTI_DOWNLOAD';
export const AE_PLAYER_ACHIEVEMENTS_USE_NEW_UX =
  'AE.PLAYER_ACHIEVEMENTS.USE_NEW_UX';
export const NEW_COREVIZ_ROUTES_ENABLED = 'NEW_COREVIZ_ROUTES_ENABLED';
export const REMOTE_COMMANDS_ENABLED = 'REMOTE_CALLS_ENABLED';
export const EXCHANGE_MARKETPLACE_ENABLED = 'MARKETPLACE.EXCHANGE_VIEW_ENABLED';
export const EXPORT_SERVER_LOGS = 'EXPORT_SERVER_LOGS';
export const MATCHMAKING_RSDOCS_UPLOAD_ENABLED =
  'MATCHMAKING_RSDOCS_UPLOAD_ENABLED';
export const MATCHMAKING_MATCH_VIEWER_ENABLED =
  'MATCHMAKING.MATCH_VIEWER_ENABLED';
export const EVENT_FILTERS_ENABLED = 'EM.EVENT_FILTERS_ENABLED';
export const INFORMATIONAL_EVENTS_ENABLED = 'EM.INFORMATIONAL_EVENTS_ENABLED';
export const EVENT_MANAGER_EVENTS_ENABLED = 'EM.EVENT_MANAGER_EVENTS_ENABLED';
export const PLAYER_ACCOUNTS_DASHBOARD = 'PLAYER.ACCOUNTS_DASHBOARD';
export const EM_USE_NEW_EVENTS = 'EM.USE_NEW_EVENTS';
export const IP_CONTROL_NOTES_ENABLED = 'IP_CONTROL_NOTES_ENABLED';
export const POOLED_OBJECTS_USE_NEW_SEARCH = 'POOLED_OBJECTS_USE_NEW_SEARCH';
export const LOGINQUEUE_ENABLED = 'LOGINQUEUE_ENABLED';
export const LOGINQUEUE_VIP_PROPAGATION_ENABLED =
  'LOGINQUEUE_VIP_PROPAGATION_ENABLED';
export const FEATURE_FLAG_VIEWER_PERM = 'FEATURE_FLAG_VIEWER_PERM';
export const PERMISSION_HELPER_VIEWER_PERM = 'PERMISSION_HELPER_VIEWER_PERM';
export const LOCALIZED_STRINGS_ENABLED = 'LOCALIZED_STRINGS.VIEW_ENABLED';
export const ACCOUNT_AUDIT_LOGS_ENABLED = 'ACCOUNT_AUDIT_LOGS.VIEW_ENABLED';

export const GVS_ENABLED = 'GVS.ENABLED';
