export const STAT_CLEAR_CHART = 'GRAPH.STAT_CLEAR_CHART';
export const STAT_DATA_FETCH = 'GRAPH.STAT_DATA_FETCH';
export const STAT_DATA_FETCH_SUCCESS = 'GRAPH.STAT_DATA_FETCH_SUCCESS';
export const STAT_DATA_INITIAL_FETCH = 'GRAPH.STAT_DATA_INITIAL_FETCH';
export const STAT_DATA_INITIAL_FETCH_SUCCESS =
  'GRAPH.STAT_DATA_INITIAL_FETCH_SUCCESS';
export const STAT_DATA_FETCH_FAILED = 'GRAPH.STAT_DATA_FETCH_FAILED';
