export const FETCH_ACTIVE_TEST_PENDING = 'activeTest/FETCH_ACTIVE_TEST_PENDING';
export const FETCH_ACTIVE_TEST_SUCCESS = 'activeTest/FETCH_ACTIVE_TEST_SUCCESS';
export const FETCH_ACTIVE_TEST_ERROR = 'activeTest/FETCH_ACTIVE_TEST_ERROR';

export const SET_ACTIVE_TEST_APPROVERS = 'activeTest/SET_ACTIVE_TEST_APPROVERS';
