export const CHALLENGE_GENERATORS_FETCH = 'security/CHALLENGE_GENERATORS_FETCH';
export const CHALLENGE_GENERATORS_FETCH_SUCCESS =
  'security/CHALLENGE_GENERATORS_FETCH_SUCCESS';

export const CHALLENGE_GENERATOR_ADD = 'security/CHALLENGE_GENERATOR_ADD';

export const CHALLENGE_GENERATOR_UPDATE = 'security/CHALLENGE_GENERATOR_UPDATE';

export const CHALLENGE_GENERATOR_DELETE = 'security/CHALLENGE_GENERATOR_DELETE';
