export const ACTIVE_RULESET_FETCH = 'achievements/ACTIVE_RULESET_FETCH';
export const ACTIVE_RULESET_FETCH_SUCCESS =
  'achievements/ACTIVE_RULESET_FETCH_SUCCESS';

export const ACTIVE_RULESET_ACHIEVEMENTS_FETCH =
  'achievements/ACTIVE_RULESET_ACHIEVEMENTS_FETCH';
export const ACTIVE_RULESET_ACHIEVEMENTS_FETCH_SUCCESS =
  'achievements/ACTIVE_RULESET_ACHIEVEMENTS_FETCH_SUCCESS';
export const ACTIVE_RULESET_ACHIEVEMENTS_FETCH_FAILED =
  'achievements/ACTIVE_RULESET_ACHIEVEMENTS_FETCH_FAILED';
