export const STORAGE_FILENAMES_FETCH = 'security/STORAGE_FILENAMES_FETCH';
export const STORAGE_FILENAMES_FETCH_SUCCESS =
  'security/STORAGE_FILENAMES_FETCH_SUCCESS';

export const STORAGE_FILENAME_ADD = 'security/STORAGE_FILENAME_ADD';
export const STORAGE_FILENAME_ADD_SUCCESS =
  'security/STORAGE_FILENAME_ADD_SUCCESS';
export const STORAGE_FILENAME_ADD_FAILED =
  'security/STORAGE_FILENAME_ADD_FAILED';

export const STORAGE_FILENAME_DELETE = 'security/STORAGE_FILENAME_DELETE';
export const STORAGE_FILENAME_DELETE_SUCCESS =
  'security/STORAGE_FILENAME_DELETE_SUCCESS';

export const STORAGE_FILENAME_ADD_MODAL_OPEN =
  'security/STORAGE_FILENAME_ADD_MODAL_OPEN';
export const STORAGE_FILENAME_ADD_MODAL_CLOSE =
  'security/STORAGE_FILENAME_ADD_MODAL_CLOSE';
